let questions = [
    ['Tom: How are you? Steve: ____', 'Fine, thanks', 'I’m Steve', 'Yes please'],
    ['Jane: What are these? Liz:_____my business cards', 'They’re', 'This is', 'It’s'],
    ['Are you married ___ single?', 'and', 'or', 'but'],
    ['What’s your email ______ ?', 'address', 'name', 'number'],
    ['My sister______', 'is ten', 'is ten years', 'has ten years'],
    ['This is my boyfriend_______French', 'He’s', 'She’s', 'It’s'],
    ['I’m _______taxi-driver', 'any', 'an', 'a'],
    ['My teacher’s from Canada, and ______ name’s Lisa.', 'your', 'our', 'her'],
    ['Cambridge ______ a beautiful city.', 'be', 'are', 'is'],
    ['John and Tom are ________ friends.', 'Peter', 'Peter’s', 'of Peter'],
    ['What’s your _______ sport?', 'important', 'favourite', 'beautiful'],
    ['Jim ______ got a car.', 'hasn’t', 'isn’t', 'haven’t'],
    ['Excuse me. _______ got the time, please?', 'You have', 'Are you', 'Have you'],
    ['Joe:When’s our next lesson? Steve: _______ Wednesday.', 'In', 'On', 'At'],
    ['I can _________Spanish.', 'speaking', 'to speak', 'speak'],
    ['Jane: Is there a bus stop near here? Sue: ______ .', 'Yes, there’s', 'Yes, there is', 'Yes, there are'],
    ['Anna ________ in a bank.', 'work', 'works', 'is work', 'working'],
    ['Let’s _____ tennis today.', 'play', 'to play', 'playing', 'plays'],
    ['What time _____ get up in the morning?', 'you', 'do you', 'are you', 'you do'],
    ['Mel loves snow but Tom doesn’t ______ it.', 'likes', 'like', 'liking', 'to like'],
    ['Hi George! ______ a good weekend?', 'Did you have', 'Have you got', 'Had you got', 'Do you have'],
    ['________to go for a pizza this evening?', 'Do you like', 'What do you want', 'How about', 'Would you like'],
    ['I _______ to Italy for my holiday last year.', 'went', 'go', 'was', 'were'],
    ['I _______ 18 years old when I started my first job.', 'were', 'had', 'was', 'did'],
    ['I didn’t ______ TV last night.', 'watched', 'watching', 'watch', 'not watched'],
    ['My grandfather was born eighty years _____.', 'since', 'last', 'ago', 'when'],
    ['Sorry, I haven’t got _____ coffee. Is tea OK?', 'some', 'any', 'many', 'a'],
    ['Waiter:A nything else, sir?Customer ______. ', 'That’s all, thanks', 'Here you are', 'No, it isn’t', 'You’re welcome'],
    ['_____ is this T-shirt?', 'How many', 'How much', 'How price'],
    ['There aren’t _____ new houses in that street.', 'many', 'much', 'some', 'a lot'],
    ['Hello, _____ I speak to Jane, please?', 'do', 'will', 'can', 'am'],
    ['Look! It _____ .', 'rains', 'raining', 'does rain', 'is raining'],
    ['London is _____ expensive than New York.', 'more', 'very', 'too', 'quite'],
    ['Alex loves giving presents. He’s very _____ .', 'selfish', 'shy', 'lazy', 'generous'],
    ['What’s _____ ? You look upset.', 'bad', 'wrong', 'happen', 'matter'],
    ['What _____ the food like at the party last night?', 'did', 'had', 'was', 'were'],
    ['If you want to get fit, you _____ do more sport.', 'will', 'would', 'should', 'have'],
    ['Jeff and Nancy _____ to watch a film tonight.', 'are going', 'is going', 'going'],
    ['Have you ever _____ to Australia?', 'been', 'go', 'be', 'went'],
    ['John ______ his wife in 2009.', 'has met', 'met', 'did he meet', 'was met'],
    ['Jane is the _____ girl in her class.', 'richer', 'more popular', 'worse', 'happiest'],
    ['It was nice to meet you. See you _____ , I hope.', 'later', 'more', 'always', 'longer'],
    ['I’m ______ sorry, but I can’t come to your party tonight.', 'much', 'awful', 'really', 'such'],
    ['I enjoy _____ because I like laughing.', 'love stories', 'comedies', 'action films', 'science fiction films'],
    ['I’m sure _____ a great time at the party next Saturday.', 'we’ll have', 'we’re having', 'we have', 'we go to have'],
    ['Are you going shopping? _____ with you if you like.', 'I’ll come', 'I come', 'I’m coming', 'I can be coming'],
    ['_____ anything next Friday?', 'Do you', 'Do you do', 'Did you', 'Are you doing'],
    ['Excuse me, I ______ if you could show me the way to the train station?', 'would like', 'wonder', 'may ask', 'hope'],
    ['How much time do you ______ doing your English homework?', 'work', 'give', 'make', 'spend'],
    ['In England people usually _____ hands when they first meet.', 'give', 'shake', 'take', 'put'],
    ['Hurry up or we’ll ______ our train!', 'lose', 'fail', 'catch', 'miss'],
    ['I was so _______ yesterday because I fell asleep in class!', 'calm', 'nervous', 'happy', 'embarrassed'],
    ['Many types of watches ______ in Switzerland.', 'are made', 'made', 'are making', 'is made'],
    ['Susan:I ’ve got four sisters.Ruth:_______you?', 'Do', 'Got', 'Are', 'Have'],
    ['What would you do if you ____ a million pounds?', 'win', 'would win', 'won', 'winning'],
    ['I’m trying to _____ money to buy a new car.', 'save', 'waste', 'spend', 'lend'],
    ['You’re from Liverpool, _____ ?', 'aren’t you', 'isn’t it', 'don’t you', 'you are'],
    ['You _____ to study hard if you want to pass your exams.', 'must', 'should', 'have', 'supposed'],
    ['I’m usually too ______ after work to go out.', 'furious', 'exhausted', 'fascinated', 'angry'],
    ['My parents ______ married since 1975.', 'have been', 'are', 'were', 'got'],
    ['If you go to London, the Tate Modern is really worth _____ .', 'to see', 'seeing', 'to be seen', 'see'],
    ['I _____ home yesterday when it started raining.', 'walk', 'was walking', 'have walked', 'have been walking'],
    ['People say English people tend _____ rather reserved.', 'being', 'be', 'to be', 'be'],
    ['Could you _____ me a favour please?', 'do', 'make', 'give', 'help'],
    ['Take your umbrella ______ it rains.', 'unless', 'because', 'as', 'in case'],
    ['Many new houses _____ in the town where I live.', 'build', 'have been building', 'are being built', 'are building'],
    ['______to post that card to Pete – it’s his birthday tomorrow.', 'If I were you, I’d', 'You should', 'Don’t forget', 'You’d better'],
    ['I don’t know many people _____ still smoke nowadays.', 'they', 'what', 'which', 'who'],
    ['Mary went to the party _____ of her headache.', 'although', 'in spite', 'even though', 'despite'],
    ['I think I’ve got a cold. I can’t stop _____ .', 'to sneeze', 'sneezing', 'sneeze', 'the sneezing'],
    ['If you don’t know the meaning of a word, you can ______ in a dictionary.', 'get it out', 'point it out', 'look it up', 'come up with it'],
    ['_____ I opened the window?', 'May', 'Would you mind if', 'Could', 'Do you mind'],
    ['My doctor _____ me I should eat less meat.', 'told', 'spoke to', 'said', 'told to'],
    ['William _____ me to go to the theatre with him next week.', 'offered', 'invited', 'promised', 'suggested'],
    ['Sorry, I didn’t quite _____ what you said.', 'catch', 'listen', 'take', 'know'],
    ['I wish I _____ get up early every morning!', 'didn’t have to', 'mustn’t', 'hadn’t', 'wouldn’t have to'],
    ['Jane _____ from Cambridge University with a degree in Law.', 'graduated', 'passed', 'studied', 'qualified'],
    ['Hi Jenny. How’s it _____ ?', 'making', 'getting', 'going', 'doing'],
    ['I don’t smoke now, but I _____ smoke 20 a day!', 'am used to', 'used to', 'use to', 'was used to'],
    ['Paris is _____ the Eiffel Tower.', 'famous for', 'impressed by', 'fascinated by', 'excited about'],
    ['If I _____ earlier, I wouldn’t have been late for work.', 'left', 'was leaving', 'had left', 'have left'],
    ['jack:Would you like me to help you? Sue: No it’s OK, but thanks _____. ', 'to offer', 'the offer', 'you offer', 'for offering'],
    ['The film sounded interesting, but it _____ to be really boring.', 'worked out', 'took off', 'came round', 'turned out'],
    ['This time next week I ______ on the beach on holiday!', 'will go to sit', 'am sitting ', 'will sit', 'will be sitting'],
    ['One argument ______ not smoking is that you save a lot of money!', 'in favour of', 'to agree with', 'it’d be better if', 'to make you'],
    ['I don’t ______ sides when my sisters have an argument.', 'listen', 'hear', 'take', 'do'],
    ['I have never _____ to Scotland.', 'been going', 'went', 'been', 'going'],
    ['I’m going to ask my bank for a _____ to redecorate the kitchen.', 'credit', 'loan', 'savings', 'debt'],
    ['Andrew: I ’m sorry I’m late.David: It _____ !', 'doesn’t matter', 'matters', 'never mind', 'alright'],
    ['I was _____ tired last night that I fell asleep on the sofa.', 'very', 'too', 'so', 'such'],
    ['Do you fancy _____ away for the weekend?', 'to go', 'go', 'going', 'we go'],
    ['How often do you have _____ ?', 'your hair cut', 'cut your hair', 'got your hair cut', 'hair cut'],
    ['What ______ me about Steve is that he’s always late!', 'bores', 'annoys', 'hates', 'dislikes'],
    ['By 2030 I believe we will _____ a settlement on Mars.', 'have built', 'have been building', 'be built', 'been built'],
    ['Some companies don’t _____ a profit in their first year.', 'get', 'make', 'work', 'do'],
    ['I haven’t got my keys. I _____ them at home.', 'should have left', 'must leave', 'couldn’t leave', 'must have left'],
    ['As soon as I _____ this book, I’ll help you clean the car.', 'have finished', 'will have finished', 'am going to finish', 'will finish'],
    ['Andy _____ enjoyed backpacking in the foothills of the Himalayas.', 'strongly', 'heavily', 'thoroughly', 'firmly'],
    ['Jack Reid won the award for best actor, _____ came as a surprise to many.', 'who', 'that', 'what', 'which'],
    ['______ from above, Niagara Falls look even more spectacular.', 'Seeing', 'Having seen', 'Seen', 'Been seeing'],
    ['Although the job applicant was well qualified, the Interviewers found her ______.', 'confident', 'hopeful', 'self-assured', 'arrogant'],
    ['The taxi managed to arrive on time, ______ the traffic was very heavy.', 'despite', 'whereas', 'although', 'even'],
    ['The minister was forced to _____ a press conference to deny the rumours.', 'make', 'do', 'hold', 'take'],
    ['Someone’s taken my mobile! I clearly remember _____ it on the table.', 'putting', 'to put', 'I’ve put', 'to have put'],
    ['Scientists are _____ research into creating energy from leaves.', 'putting up', 'trying on', 'taking in', 'carrying out'],
    ['Plans to build the new stadium suffered a _____ when the major sponsor withdrew his support.', 'downturn', 'breakdown', 'setback', 'backlash'],
    ['Travelling by train is _____ less stressful than driving.', 'absolutely', 'extremely', 'totally', 'considerably'],
    ['If you _____ have any further questions, please do not hesitate to contact us.', 'would', 'could', 'should', 'might'],
    ['Quite _____, I think a lot of this talk about climate change is exaggerated.', 'clearly', 'frankly', 'plainly', 'openly'],
    ['I wish I _____ go out this evening. I’d rather stay in and watch a film.', 'didn’t have to', 'haven’t to', 'hadn’t had to', 'haven’t had to'],
    ['Make sure you’ve had all the necessary injections before going into the jungle, _____ you’ll risk catching tropical diseases.', 'in case', 'otherwise', 'providing', 'unless'],
    ['Many companies are expected _____ out of business during the recession.', 'they will go', 'going', 'that they go', 'to go'],
    ['_____ the summer being so hot, sales of air-conditioners rose.', 'Because', 'As a result', 'Due to', 'Consequently'],
    ['It’s time _____ the fact that he’ll never make it as a rock musician.', 'he accepts', 'he’ll accept', 'he accepted', 'he’d accept'],
    ['The waiter _____ us the impression that he couldn’t wait to finish his shift.', 'made', 'gave', 'had', 'showed'],
    ['Kim still hasn’t got _____ to starting his essay.', 'through', 'off', 'over', 'round'],

];